### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by ChronoDK** [krones9000/KT24CheatSheet#1]
Hi, good job on this! I printed and played a game using it - love how it just has everything. The font size though, it's really small once you print it on A4! Slows down finding the info you need. This is probably not an easy change to make, but I think there are places to save a bit of space to increase the font size.

Small bug: The uppercase FLOOR and MORE under heavy barricade is a nice touch - but it's missing from the light barricade text.

**Comment by krones9000** [comment]
Thank you. I've added the FLOOR MORE thing to the backlog and will put that in the next update. 

As to the font size. You're right, it's just quite hard to do without removing content. Even removing the duplicates on the second page and spreading things out doesn't offer that much scope for space savings. I think the only way I can realistically do it would be to remove some of the content like the Killzone specific stuff. 

Maybe put it on an optional "third" page, i.e print the first one back to back for the "essentials" on a single page with the extra sheet as the additional info? I'll need to have an experiment but let me know if you've got any specific advice.

**Comment by ChronoDK** [comment]
A third sheet would be a shame, it's nice to just have one page. I think increasing the font size by 1 point at least, should be doable? There are many paragraphs with only one word one the last line - increasing the font size wont even cost on extra line there. On the Special Rule list the keywords column could be slightly slimmer.

Another, more drastic approach, could be to remove duplicate boxes and columns. Special Rules are on both pages, Cover, Terrain and Movement too.

**Comment by feuerfritas** [comment]
Looks like the sheet is using the font ConduitITCStd, I got it from https://fontsgeek.com/fonts/conduititcstd-regular and it does look like it could be increased a bit as there is some empty space around it.

Action titles and special rules could also be inlined (but still kept bold/large) to use some of the empty space around them

**Comment by krones9000** [comment]
I've done some initial drafting. I found it quite hard to get much benefit without at least bumping to font to size 10 overall.

This really does stretch the capacity of an A4 though. And so far, I've not been able to fit it all on and logically keep the **Scoring** section which feel a bit of an issue. This is where I'm at so far, trying to balance readability with fitting it all in whilst also making the font larger:

![image](https://github.com/user-attachments/assets/28b6a327-e12e-4ccc-9a8f-8e908947b9ab)

![image](https://github.com/user-attachments/assets/fff63ed5-54af-49f5-93f7-64ba1ac865fa)

Any thoughts on better ways to do it?

**Comment by ChronoDK** [comment]
Without printing, so not 100% sure, but think the font size is very readable now. I compared to my own sheet, and it looks like the same size. I have that one printed too, and going one step down in font size would not be the worst idea.

The top section on game sequence lacks a bit of readability - indentation would help. I think line spacing should be lowered too, to match the rest of the sheet. 

The explosive grenades could be put next to each other to save space.

**Comment by krones9000** [comment]
Good call, yeah I think there's plenty of space for some indentation. I'll have another play over the next couple days and do another update here before I consider rolling anything out to the main release.

**Comment by krones9000** [comment]
I have released a version 1.2 and am closing this for now. The new version splits over 2 pages and has a larger font. I'll work with that going forwards.
