### ISSUE TITLE
Part 3. is missing

### ISSUE THREAD

**Issue by VPURecover** [krones9000/KT24CheatSheet#2]
Hello !
Congrats for this wonderful work.

It seems, in PvP game sequence, part 3. is missing.
Actually, it goes 
1.Setup
2.Select operatives
4.Scouting
If I'm correct, part 3. is the "Set up operatives" step.

**Comment by krones9000** [comment]
Legend! Thank you for catching this. It seems to have dropped off in the move to the larger format. I've updated it everywhere now so should be good but let me know if you spot anything else and I'll close this ticket in a day or so if no further comment.

**Comment by krones9000** [comment]
Marking this closed for now. If you do spot anything related to this or anything else then please don't hesitate to raise another issue and I'll aim to get it fixed ASAP.

Remember, all versions of the PDF are versioned and have a link to the Github built in so you can always confirm if you're on the most recent, and hopefully therefore, most accurate release.

Thanks!
